#!/usr/bin/env python3
"""
scripts/run_calibration.py — OptiTrack Calibration Tool

Three calibration modes:

MODE 1: Depth Estimation (default, --mode depth)
    Place the CS-100 flat on the floor. The script records its pose,
    validates the L-shape geometry (8cm + 10cm edges), and estimates
    the depth from the V120:Trio middle camera to the floor plane.

MODE 2: 3-Point Frame Definition (--mode frame)
    Place the CS-100 at 3 positions to define the world coordinate frame:
      1. ORIGIN — where you want (0, 0, 0)
      2. +X AXIS — direction of +X
      3. XY PLANE — defines which way +Y points

MODE 3: Multi-Point SVD Registration (--mode svd)
    N ≥ 3 point correspondences → best-fit rigid transform via Arun's method.

Usage
-----
    cd vision_engine

    # Depth estimation (recommended first step):
    python scripts/run_calibration.py

    # 3-point frame definition:
    python scripts/run_calibration.py --mode frame

    # SVD multi-point:
    python scripts/run_calibration.py --mode svd

    # Debug — print all raw data from OptiTrack:
    python scripts/run_calibration.py --mode debug

Output
------
    config/calibration.yaml — calibration data (depth, transform, etc.)
"""

import sys
import os
import time
import argparse
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import yaml
from utils import load_config
from cv.optitrack_client import OptiTrackClient
from cv.cs100_model import CS100Geometry
from cv.depth_estimator import FloorDepthEstimator
from cv.transforms import compute_rigid_transform, apply_transform, make_transform


def save_calibration(output_path: str, data: dict):
    """Save calibration result to YAML."""
    with open(output_path, "w") as f:
        f.write("# Auto-generated by run_calibration.py\n")
        f.write(f"# Method: {data.get('method', 'unknown')}\n")
        f.write(f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        yaml.dump(data, f, default_flow_style=None)
    print(f"\n[Calibration] Saved to {output_path}")


def wait_for_body(client, preferred_name: str, timeout: float = 10.0) -> str:
    """
    Wait until at least one rigid body appears, then return the best match.

    Prints diagnostic info about what bodies are available.
    """
    print(f"[Calibration] Waiting for rigid bodies (timeout {timeout:.0f}s)...")

    start = time.time()
    bodies = {}
    while time.time() - start < timeout:
        bodies = client.get_rigid_bodies()
        if bodies:
            break
        time.sleep(0.1)

    if not bodies:
        print("\n[ERROR] No rigid bodies received from OptiTrack.")
        print("  Checklist:")
        print("    1. Is Motive running and streaming? (View → Data Streaming → check ON)")
        print("    2. Is a rigid body defined in Motive? (Select markers → right-click → Rigid Body)")
        print("    3. Is the network correct? (server_ip in scene_config.yaml)")
        print(f"    4. NatNet version: {client.natnet_version}")
        print(f"    5. Server: {client.server_app_name or 'no response'}")
        print(f"    6. Frames received: {client.get_frame_count()}")
        print(f"    7. Rigid body IDs known: {dict(client._id_to_name)}")
        return None

    # Print all available bodies
    print(f"\n[Calibration] Detected {len(bodies)} rigid body(ies):")
    for name, body in bodies.items():
        p = body.position
        q = body.quaternion
        status = "TRACKING" if body.tracking_valid else "NOT TRACKING"
        print(f"  '{name}' (id={body.id}) — {status}")
        print(f"    pos=({p[0]:.4f}, {p[1]:.4f}, {p[2]:.4f})")
        print(f"    quat=({q[0]:.4f}, {q[1]:.4f}, {q[2]:.4f}, {q[3]:.4f})")

    # Try to match the preferred name
    if preferred_name in bodies:
        print(f"\n[Calibration] Using rigid body: '{preferred_name}'")
        return preferred_name

    # Case-insensitive match
    for name in bodies:
        if name.lower() == preferred_name.lower():
            print(f"\n[Calibration] Using rigid body: '{name}' (matched '{preferred_name}' case-insensitive)")
            return name

    # Partial match (e.g., "CS-100" matches "CS-100 1" or "cs100")
    for name in bodies:
        if preferred_name.lower().replace("-", "").replace("_", "") in name.lower().replace("-", "").replace("_", ""):
            print(f"\n[Calibration] Using rigid body: '{name}' (partial match for '{preferred_name}')")
            return name

    # Fall back to first available body
    fallback = list(bodies.keys())[0]
    print(f"\n[WARNING] Preferred body '{preferred_name}' not found.")
    print(f"  Available: {list(bodies.keys())}")
    print(f"  Falling back to: '{fallback}'")
    return fallback


def record_position(client, body_name: str, label: str, num_samples: int = 60) -> np.ndarray:
    """Record the averaged position of a rigid body."""
    input(f"\n  Place the CS-100 at: {label}\n"
          f"  Keep it still and visible, then press Enter...")

    readings = []
    print(f"  Recording ({num_samples} frames)...", end="", flush=True)
    for i in range(num_samples * 2):
        bodies = client.get_rigid_bodies()
        if body_name in bodies:
            body = bodies[body_name]
            pos = body.position
            # Accept if position is finite (don't rely solely on tracking_valid)
            if np.all(np.isfinite(pos)) and np.linalg.norm(pos) < 100.0:
                readings.append(pos.copy())
                if len(readings) >= num_samples:
                    break
        time.sleep(0.033)
    print(" done.")

    if len(readings) < num_samples // 2:
        print(f"  [WARNING] Only got {len(readings)}/{num_samples} valid readings.")
        if len(readings) < 3:
            raise RuntimeError("Too few valid readings. Cannot proceed.")

    pos = np.mean(readings, axis=0)
    std = np.std(readings, axis=0)
    print(f"  Recorded: ({pos[0]:.4f}, {pos[1]:.4f}, {pos[2]:.4f}) m")
    print(f"  Std dev:  ({std[0]:.4f}, {std[1]:.4f}, {std[2]:.4f}) m")

    if np.max(std) > 0.002:
        print(f"  [WARNING] High std dev ({np.max(std)*1000:.1f} mm). "
              f"Was it moving during recording?")

    return pos


# ──────────────────────────────────────────────────────────────────────────────
# Mode: Debug — Print Raw OptiTrack Data
# ──────────────────────────────────────────────────────────────────────────────

def run_debug(client):
    """Continuously print all rigid body data from OptiTrack."""
    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║              OptiTrack Debug — Raw Data Stream                      ║
╠══════════════════════════════════════════════════════════════════════╣
║  Printing all rigid body data. Press Ctrl+C to stop.               ║
╚══════════════════════════════════════════════════════════════════════╝
""")
    print(f"  Server: {client.server_app_name or 'unknown'}")
    print(f"  NatNet version: {client.natnet_version}")
    print(f"  Rigid body IDs: {dict(client._id_to_name)}")
    print()

    try:
        while True:
            bodies = client.get_rigid_bodies()
            if not bodies:
                print(f"  [No bodies] frames={client.get_frame_count()}", end="\r")
            else:
                lines = []
                for name, body in bodies.items():
                    p = body.position
                    q = body.quaternion
                    tv = "OK" if body.tracking_valid else "LOST"
                    lines.append(
                        f"  {name} (id={body.id}) [{tv}] "
                        f"pos=({p[0]:+.4f}, {p[1]:+.4f}, {p[2]:+.4f}) "
                        f"quat=({q[0]:+.3f}, {q[1]:+.3f}, {q[2]:+.3f}, {q[3]:+.3f})"
                    )
                print(f"  frame={client.get_frame_count()}")
                for line in lines:
                    print(line)
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\n[Debug] Stopped.")


# ──────────────────────────────────────────────────────────────────────────────
# Mode 1: Depth Estimation (CS-100 L-Shape on Floor)
# ──────────────────────────────────────────────────────────────────────────────

def calibrate_depth(client, body_name: str, config: dict) -> dict:
    """
    Estimate camera-to-floor depth using CS-100 placed flat on the floor.
    """
    depth_cfg = config.get("depth_estimation", {})
    objects_cfg = config.get("objects", {})
    cs100_cfg = objects_cfg.get(body_name, objects_cfg.get("CS-100", {}))

    cs100 = CS100Geometry(
        short_arm_length=cs100_cfg.get("short_arm_length", 0.08),
        long_arm_length=cs100_cfg.get("long_arm_length", 0.10),
        distance_tolerance_mm=depth_cfg.get("distance_tolerance_mm", 2.0),
    )

    estimator = FloorDepthEstimator(cs100_model=cs100)

    num_samples = depth_cfg.get("num_samples", 60)
    flatness_threshold = depth_cfg.get("flatness_threshold_deg", 5.0)

    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║              CS-100 Floor Depth Estimation                          ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                     ║
║  Place the CS-100 FLAT on the FLOOR under the V120:Trio.            ║
║                                                                     ║
║  The L-shape geometry (8cm + 10cm edges) will be validated,         ║
║  and the camera-to-floor depth will be estimated.                   ║
║                                                                     ║
║  Requirements:                                                      ║
║    - CS-100 must be flat (tilt < {flatness_threshold:.0f}°)                         ║
║    - All 3 markers must be visible to the V120:Trio                 ║
║    - Keep the CS-100 still during recording                         ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    input("  Place CS-100 flat on the floor, then press Enter...")

    print(f"  Recording {num_samples} frames...")
    valid_count = 0
    skip_count = 0
    no_body_count = 0
    bad_pos_count = 0

    for attempt in range(num_samples * 3):
        bodies = client.get_rigid_bodies()

        if body_name not in bodies:
            no_body_count += 1
            time.sleep(0.033)
            continue

        body = bodies[body_name]
        pos = body.position
        quat = body.quaternion

        # Validate data quality — accept even if tracking_valid is False,
        # as long as the position is finite and reasonable.
        if not np.all(np.isfinite(pos)) or not np.all(np.isfinite(quat)):
            bad_pos_count += 1
            time.sleep(0.033)
            continue

        if np.linalg.norm(pos) > 100.0:
            bad_pos_count += 1
            time.sleep(0.033)
            continue

        # Quaternion must be non-zero
        if np.linalg.norm(quat) < 0.5:
            bad_pos_count += 1
            time.sleep(0.033)
            continue

        estimator.record_sample(pos, quat)
        valid_count += 1

        # Progress indicator
        if valid_count % 10 == 0:
            print(f"    {valid_count}/{num_samples} samples collected...")

        if valid_count >= num_samples:
            break

        time.sleep(0.033)

    print(f"  Done: {valid_count} valid, {no_body_count} no-body, {bad_pos_count} bad-data")

    if valid_count == 0:
        # Print detailed diagnostics
        print(f"\n[ERROR] 0 valid samples collected.")
        print(f"  Diagnostics:")
        print(f"    Body name searched: '{body_name}'")
        print(f"    Frames received by client: {client.get_frame_count()}")
        print(f"    Known rigid body IDs: {dict(client._id_to_name)}")
        bodies = client.get_rigid_bodies()
        if bodies:
            print(f"    Bodies currently available: {list(bodies.keys())}")
            for n, b in bodies.items():
                print(f"      '{n}': tracking_valid={b.tracking_valid}, "
                      f"pos={b.position}, quat={b.quaternion}")
        else:
            print(f"    No bodies currently available")
        raise RuntimeError(
            f"No valid readings. Is '{body_name}' defined in Motive and visible?"
        )

    if valid_count < num_samples // 2:
        print(f"  [WARNING] Only {valid_count}/{num_samples} valid readings.")

    # Compute depth
    result = estimator.compute(min_samples=min(valid_count, 3))
    estimator.print_report()

    # Check flatness
    if result["flatness_deg"] > flatness_threshold:
        print(f"  [WARNING] CS-100 is tilted {result['flatness_deg']:.1f}° "
              f"(threshold: {flatness_threshold}°). "
              f"Place it flatter for better accuracy.")

    # Check geometry validation
    v = result["marker_validation"]
    if not v["is_valid"]:
        print(f"  [WARNING] Marker distances don't match expected geometry!")
        print(f"    Short arm: {v['short_arm_dist_m']*100:.2f} cm "
              f"(expected {cs100.short_arm_length*100:.0f} cm)")
        print(f"    Long arm:  {v['long_arm_dist_m']*100:.2f} cm "
              f"(expected {cs100.long_arm_length*100:.0f} cm)")

    # Build calibration data
    cal_data = {
        "method": "depth",
        "camera_to_floor_depth_m": result["camera_to_floor_depth"],
        "floor_z": result["floor_z"],
        "floor_point": result["floor_point"],
        "floor_normal": result["floor_normal"],
        "flatness_deg": result["flatness_deg"],
        "num_samples": result["num_samples"],
        "position_std_mm": result["position_std_mm"],
        "marker_validation": {
            "short_arm_dist_cm": round(v["short_arm_dist_m"] * 100, 2),
            "long_arm_dist_cm": round(v["long_arm_dist_m"] * 100, 2),
            "hypotenuse_dist_cm": round(v["hypotenuse_dist_m"] * 100, 2),
            "short_arm_error_mm": round(v["short_arm_error_mm"], 2),
            "long_arm_error_mm": round(v["long_arm_error_mm"], 2),
            "hypotenuse_error_mm": round(v["hypotenuse_error_mm"], 2),
            "is_valid": v["is_valid"],
        },
    }
    return cal_data


# ──────────────────────────────────────────────────────────────────────────────
# Mode 2: 3-Point Frame Definition
# ──────────────────────────────────────────────────────────────────────────────

def calibrate_3point_frame(client, body_name: str, table_height: float) -> dict:
    """Define the world coordinate frame from 3 placements of the CS-100."""
    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║           3-Point Frame Calibration (CS-100)                        ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                     ║
║  Place the CS-100 at 3 positions:                                   ║
║    1. ORIGIN   — where you want (0, 0, 0)                          ║
║    2. +X AXIS  — direction of +X                                    ║
║    3. XY PLANE — defines +Y direction                               ║
║                                                                     ║
║  Z axis = X × Y (right-hand rule, points up).                      ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    p1 = record_position(client, body_name, "ORIGIN (where you want 0,0,0)")
    p2 = record_position(client, body_name, "+X DIRECTION")
    p3 = record_position(client, body_name, "XY PLANE (off the X axis, defines +Y side)")

    x_vec = p2 - p1
    x_len = np.linalg.norm(x_vec)
    if x_len < 0.01:
        raise RuntimeError(f"Points 1 and 2 too close ({x_len*1000:.1f} mm).")
    x_axis = x_vec / x_len

    y_temp = p3 - p1
    y_temp_len = np.linalg.norm(y_temp)
    if y_temp_len < 0.01:
        raise RuntimeError(f"Points 1 and 3 too close ({y_temp_len*1000:.1f} mm).")

    z_axis = np.cross(x_axis, y_temp / y_temp_len)
    z_len = np.linalg.norm(z_axis)
    if z_len < 0.01:
        raise RuntimeError("Points are nearly collinear.")
    z_axis = z_axis / z_len

    if z_axis[2] < 0:
        z_axis = -z_axis

    y_axis = np.cross(z_axis, x_axis)
    y_axis = y_axis / np.linalg.norm(y_axis)

    R_opti_to_world = np.column_stack([x_axis, y_axis, z_axis])
    R = R_opti_to_world.T
    target_origin = np.array([0.0, 0.0, table_height])
    t = target_origin - R @ p1
    T = make_transform(R, t)

    p1_world = apply_transform(T, p1)
    p2_world = apply_transform(T, p2)
    p3_world = apply_transform(T, p3)

    print(f"\n{'='*60}")
    print("3-Point Frame Calibration Result")
    print(f"{'='*60}")
    print(f"\n  Origin → +X:  {x_len*100:.1f} cm")
    print(f"  Origin → XY:  {y_temp_len*100:.1f} cm")
    print(f"\n  Verification (world frame):")
    print(f"    Origin:  ({p1_world[0]:.4f}, {p1_world[1]:.4f}, {p1_world[2]:.4f})")
    print(f"    +X dir:  ({p2_world[0]:.4f}, {p2_world[1]:.4f}, {p2_world[2]:.4f})")
    print(f"    XY pt:   ({p3_world[0]:.4f}, {p3_world[1]:.4f}, {p3_world[2]:.4f})")

    cal_data = {
        "method": "frame",
        "transform": T.tolist(),
        "table_height": float(table_height),
        "x_axis_distance_m": float(x_len),
        "xy_axis_distance_m": float(y_temp_len),
    }
    return cal_data


# ──────────────────────────────────────────────────────────────────────────────
# Mode 3: Multi-Point SVD Registration
# ──────────────────────────────────────────────────────────────────────────────

def calibrate_svd(client, body_name: str, min_points: int) -> dict:
    """N-point SVD registration."""
    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║              SVD Multi-Point Calibration                            ║
╠══════════════════════════════════════════════════════════════════════╣
║  1. Place CS-100 at a known position                                ║
║  2. Enter known (x, y, z) in meters                                 ║
║  3. Press Enter to record                                           ║
║  4. Repeat for at least {min_points} positions                                ║
║  5. Type 'done' when finished                                       ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    optitrack_points = []
    target_points = []

    while True:
        idx = len(optitrack_points) + 1
        print(f"--- Point {idx} ---")
        user_input = input("  Target (x, y, z) in meters [or 'done']: ").strip()
        if user_input.lower() in ("done", "d", "quit", "q"):
            break

        try:
            parts = user_input.replace(",", " ").replace("(", "").replace(")", "").split()
            target_xyz = [float(p) for p in parts]
            if len(target_xyz) != 3:
                raise ValueError("Need exactly 3 values")
        except (ValueError, IndexError):
            print(f"  [Error] Enter 3 numbers, e.g.: 0.5 0.0 0.7")
            continue

        try:
            optitrack_pos = record_position(client, body_name, f"target ({user_input})")
        except RuntimeError as e:
            print(f"  [Error] {e}")
            continue

        optitrack_points.append(optitrack_pos)
        target_points.append(np.array(target_xyz))
        print(f"  Points recorded: {len(optitrack_points)}\n")

    if len(optitrack_points) < min_points:
        raise RuntimeError(f"Need at least {min_points} points, got {len(optitrack_points)}.")

    source = np.array(optitrack_points)
    target = np.array(target_points)
    T, rms_error = compute_rigid_transform(source, target)

    print(f"\n{'='*60}")
    print("SVD Calibration Result")
    print(f"{'='*60}")
    print(f"  Points: {len(optitrack_points)}, RMS error: {rms_error*1000:.1f} mm")

    cal_data = {
        "method": "svd",
        "transform": T.tolist(),
        "rms_error": float(rms_error),
        "num_points": len(optitrack_points),
    }
    return cal_data


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Calibrate OptiTrack V120:Trio using CS-100"
    )
    parser.add_argument(
        "--config",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "scene_config.yaml"),
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "calibration.yaml"),
    )
    parser.add_argument(
        "--body", default=None,
        help="Rigid body name in Motive (default: auto-detect from config)",
    )
    parser.add_argument(
        "--mode", choices=["depth", "frame", "svd", "debug"], default="depth",
        help="Calibration mode: 'depth' (default), 'frame', 'svd', or 'debug'",
    )
    parser.add_argument(
        "--table-height", type=float, default=0.0,
        help="Table height for frame mode (default: 0.0)",
    )
    parser.add_argument(
        "--min-points", type=int, default=3,
        help="Min correspondences for SVD mode (default: 3)",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    optitrack_cfg = config.get("optitrack", {})

    client = OptiTrackClient(
        server_ip=optitrack_cfg.get("server_ip", "192.168.0.101"),
        local_ip=optitrack_cfg.get("local_ip", "0.0.0.0"),
        multicast_ip=optitrack_cfg.get("multicast_ip", "239.255.42.99"),
        command_port=optitrack_cfg.get("command_port", 1510),
        data_port=optitrack_cfg.get("data_port", 1511),
    )
    client.start()
    time.sleep(1.5)

    print(f"[Calibration] NatNet version: {client.natnet_version}")
    print(f"[Calibration] Server: {client.server_app_name or 'no response'}")
    print(f"[Calibration] Frames received: {client.get_frame_count()}")

    # Debug mode — just print data and exit
    if args.mode == "debug":
        run_debug(client)
        client.stop()
        return

    # Determine body name
    preferred_name = args.body
    if preferred_name is None:
        cal_cfg = config.get("calibration", {})
        preferred_name = cal_cfg.get("tool_body", "CS-100")

    body_name = wait_for_body(client, preferred_name, timeout=10.0)
    if body_name is None:
        client.stop()
        return

    try:
        if args.mode == "depth":
            cal_data = calibrate_depth(client, body_name, config)
        elif args.mode == "frame":
            cal_data = calibrate_3point_frame(client, body_name, args.table_height)
        else:
            cal_data = calibrate_svd(client, body_name, args.min_points)
    except RuntimeError as e:
        print(f"\n[Error] {e}")
        client.stop()
        return

    save_calibration(args.output, cal_data)
    client.stop()

    print(f"\nCalibration complete. Saved to:")
    print(f"  {os.path.abspath(args.output)}")


if __name__ == "__main__":
    main()
